### ISSUE TITLE
Train & inference guide

### ISSUE THREAD

**Issue by rogermiranda1000** [litagin02/rvc-tts-webui#27]
I'll open this issue to address @AIhasArrived issue opened in [issue 12](https://github.com/litagin02/rvc-tts-webui/issues/12#issuecomment-1786141460).

The first thing: yes, you will be able to get very decent voices with this tool, as you can see in [my custom tts](https://gist.github.com/rogermiranda1000/083eec93ebbdd1dcf8edea51cfc16bc5/2930f1fb1f85ed128840ad0135ea1485bcc0b20d#voices). So you are doing something wrong.

First of all you'll have to train the RVC model. If you need help on that you should ask in [their GitHub repo](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI), but I recommend you this tutorial, that was the one I followed: [Use AI to Clone ANY Voice & Sing ANY Song for FREE | RVC WebUI Tutorial, from Nerdy Rodent](https://youtu.be/-JcvdDErkAU?si=ZbA4GOSePF_nGtDj). For reference, 200 epochs are ok for ~5 minutes of audio, but if you have more than 1h I'll put something higher.

Once you have trained the model you'll have to create a folder inside `weights` with the name of the model, and copy the .pth (inside RVC's `weights` folder) and the `.index` that has the biggest size (you'll find the `.index` in the RVC's `logs` folder).

Then select a speaker that suits the trained voice (some of them are better than others), and you're done.

**Comment by AIhasArrived** [comment]
I will watch the video and tell you how I do. I think the best thing to do, TO EASE the minds, is to have the same data to process (maybe use the same audio from some youtube video) and train on it, and if someone gets it then someone else could try to reproduce it step by step with the exact paramterts, the fact that they have the same DATA , will allow the person to FINALLY get a real good result (supposedly, I really hope what you are saying it true, I will have to hear it with my mind).
As for their repo, it seems they are on vacation, I had already made 2 issues, one related to installation manually (the release worked in the end), and another about a warning message. 
My main problem seem to be : making models that will produce voices very similar the to the original voice.
You mentioned 200 epochs for 5 minutes, what about 10 minutes , and 15 minutes? Or is it trial and error in reality? Not always clear how much you need exaclty.
__
I will follow the tutorial you suggested and answer again, or edit this comment to report my results. Thanks for the post.

**Comment by rogermiranda1000** [comment]
> You mentioned 200 epochs for 5 minutes, what about 10 minutes , and 15 minutes? Or is it trial and error in reality?

The model will eventually convergence if you set a high enough number, but it can take a lot of time. Still, if with 200 epochs the voice is "very similar to the original" something on your setup is wrong.

**Comment by AIhasArrived** [comment]
you mean "if it is NOT " very original, right?
Ok I am investigating, and this is the first thing I noticed when watching that tutorial, it's about the first step on the training phase,  the button "Process Data",
So I my data is on this path:
![image](https://github.com/litagin02/rvc-tts-webui/assets/148225825/e24ac473-f85d-4e65-a3c3-8a5fcfecb965)

When pressing the button, I noticed that the youtuber has obtained lot of processed voices/wav files I suppose? 
Mine stayed the same, I mean the folder stays like this:
![image](https://github.com/litagin02/rvc-tts-webui/assets/148225825/75fdc259-18e4-4c5d-99b5-c5ec7f61e0fb)
Could you confirm to me that your path to the audio stays the same after pressing the "process data" button? Or is there something wrong with my setup?
This is what the terminal shows:
![image](https://github.com/litagin02/rvc-tts-webui/assets/148225825/aa8fb7cf-422e-4c06-92c4-c7c75b201d3e)

do you have the same logs for that precise button?
I will continue the video.

**Comment by rogermiranda1000** [comment]
@AIhasArrived use `.wav` files. Maybe that's why it's not working, because it's not picking the files.

**Comment by AIhasArrived** [comment]
I ended up finding that the tool i was using demucs has an option to produce wav instead of flac.
However I was making during that time a model with 300 epochs, and when I tried it with tts (tvc-tts edge) it gave surprisngly CLOSE To the original voice audios :D ! (despite training on flacs)
However, the tutorial you linked, showed how to use "inference" which I did not use in the past, I tried using the same music he used (Ponyo) and unfortunately and was a bit disspaointed, the music output did not come out good, the voice wa was a bit broken!
So I am now wondering why the actual models made were able to produce good voices (for usual speaking), but they would not produce good inference music. Oh well. If you have any extra info/guidance/idea on this, I will hear it.

**Comment by rogermiranda1000** [comment]
> So I am now wondering why the actual models made were able to produce good voices (for usual speaking), but they would not produce good inference music.

Music inference is hard. Some of them will give better results than others (for example, calm music vs metal).
One music that works well is "Cupid", by fifty fifty. You can try that (remember that you'll have to first split instruments and vocals! You'll have to infere the vocals, then merge the files)
