### ISSUE TITLE
KeyError: 'config'

### ISSUE THREAD

**Issue by rogermiranda1000** [litagin02/rvc-tts-webui#5]
The line `tgt_sr = cpt["config"][-1]` raises the error `KeyError: 'config'`. While checking for the keys (`print(cpt.keys())`) I could find only those: `['model', 'iteration', 'optimizer', 'learning_rate']`.

Also, my `weights` folder looks like this (model created with the [latest RVC release](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases/tag/updated0618v2)):
```
../../singer/Retrieval-based-Voice-Conversion/weights/
├── nedia-v3.2_e100_s4400.pth
├── nedia-v3.2_e120_s5280.pth
[...]
├── nedia-v3.2_e60_s2640.pth
├── nedia-v3.2_e80_s3520.pth
└── nedia-v3.2.pth
```

So, instead of the `weights` folder I used the `logs`:
```
./../singer/Retrieval-based-Voice-Conversion/logs/
├── mute
│   ├── 0_gt_wavs
│   ├── 1_16k_wavs
│   ├── 2a_f0
│   ├── 2b-f0nsf
│   ├── 3_feature256
│   └── 3_feature768
└── nedia-v3.2
    ├── 0_gt_wavs
    ├── 1_16k_wavs
    ├── 2a_f0
    ├── 2b-f0nsf
    ├── 3_feature768
    ├── added_IVF4342_Flat_nprobe_1_nedia-v3.2_v2.index
    ├── config.json
    ├── D_2333333.pth
    ├── eval
    ├── events.out.tfevents.1691012539.roger-Alienware.125840.0
    ├── extract_f0_feature.log
    ├── filelist.txt
    ├── G_2333333.pth
    ├── preprocess.log
    ├── total_fea.npy
    ├── trained_IVF4342_Flat_nprobe_1_nedia-v3.2_v2.index
    └── train.log
```

**Comment by rogermiranda1000** [comment]
I managed to make it work by copying the latest `.pth` from the `weights` folder into `logs/<speaker>`, and then changing the line that gets the pth file to:
```
pth_files = [
        os.path.join(model_root, model_name, f)
        for f in os.listdir(os.path.join(model_root, model_name))
        if f == model_name + '.pth'
    ]
```
Still, should be worth to investigate why I have a different folder system than the others.

**Comment by rogermiranda1000** [comment]
Oh nvm, I just realized in the README that "Locate your RVC models in weights directory" means "**Place** your RVC models in weights directory", my bad.

**Comment by litagin02** [comment]
Oh I'm sorry my English was wrong. I corrected. Thank you.

**Comment by AIhasArrived** [comment]
@rogermiranda1000 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
